### ISSUE TITLE
Задание по Линукс

### ISSUE THREAD

**Issue by alievgithub** [vlasenckov/MIPT_py_3_term#2]
КИРИЛЛ, КАК ДЕЛАТЬ 6-9 ПУНКТ!!!???

**Comment by kirvlasenkov** [comment]
Добрый день, Артем. 
Спасибо за ваше обращение. Могу только посоветовать перейти [cюда](http://cs.mipt.ru/advanced_python/lessons/lab2.html), так как именно так и планирую сделать эти задания сам.

**Comment by alievgithub** [comment]
Спасибо, но я уже переходил и информации там крайне пало по PATH, поэтому мне эт не помогло решить проблему, поэтому рассчитываю на вас, Кирилл, а еще на Рамиля, Глеба и всю группу!
